---
title: "README"
author: "Isabelle Boulangeat"
date: "`r format(Sys.time(), '%d/%m/%y')`"
output:
  html_document:
    keep_md: yes
    variant: markdown_github
  pdf_document: default
editor_options:
  chunk_output_type: console
always_allow_html: yes
---

```{r setup, include=FALSE}
library(knitr)
# library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
# library(Jmisc)
library(tidyr)
sapply(list.files("R_fct"), function(x)source(paste0("R_fct/",x)))
require(sp)
require(dplyr)
require(ggplot2)
require(ggmap)
require(sf)
```

## Chargement des données
```{r load}
pts = read.table("_data/export_478_24032021_151335.txt", sep='\t', h=TRUE)
sites_points = pts %>% dplyr::select(id_releve, date_releve_deb, lon_wgs84, lat_wgs84, x_l93, y_l93, id_precision)

sites_points1 = sites_points %>% filter(!is.na(lon_wgs84))
coordinates(sites_points1)= c("lon_wgs84","lat_wgs84")
proj4string(sites_points1) = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
#sites_points1 = spTransform(sites_points1, CRS("+init=epsg:4326"))

sites_df <- data.frame(sites_points1)
require(tmaptools)
bbox <- tmaptools::bb(xlim = c(5.68,  8.40), ylim = c(43.60, 46.12))

```


## Répartition des observations
```{r obs,fig=TRUE}
bbox_map <- c(left = 5.68,  right = 8.40, bottom = 43.60, top= 46.12)
p <- ggmap(get_map(bbox_map, source = 'osm',
                         maptype ='terrain',
                         color = 'color'))
p + geom_point(data=sites_df,  aes(x=lon_wgs84, y=lat_wgs84), size=1) 
```
```{r leaflet, fig = TRUE}
library(leaflet) 
leaflet(sites_df)%>%
  addProviderTiles("OpenStreetMap.HOT")%>%
  setView(lng=5.5,lat=45,zoom=6) %>%
  addCircleMarkers(lng = ~lon_wgs84, lat = ~lat_wgs84, popup = ~date_releve_deb, radius = 1, opacity = 0.8, color = "red")
```

## données préparées
```{r load2}
data_env_topo_clim = readRDS("data_env_topo_clim.rds")
# BIO1 = Annual Mean Temperature
# BIO2 = Mean Diurnal Range (Mean of monthly (max temp - min temp))
# BIO3 = Isothermality (BIO2/BIO7) (×100)
# BIO4 = Temperature Seasonality (standard deviation ×100)
# BIO5 = Max Temperature of Warmest Month
# BIO6 = Min Temperature of Coldest Month
# BIO12 = Annual Precipitation
# BIO15 = Precipitation Seasonality (Coefficient of Variation)
# gdd0 = heat sum of all days above the 0°C temperature accumulated over 1 year
# gsl = Length of the growing season (TREELIM)
# gsp = precipitation sum accumulated on all days during the growing season )TREELIM)
# gst = Mean temperature of all growing season days (TREELIM)
# ngd0 = Number of days at which tas > 0°C
# npp = Calculated based on the ‘Miami model’
# scd = Number of days with snowcover (TREELIM)

data_env_topo_clim$obs$response = 1
data_env_topo_clim$bg$response = 0

dataset = rbind(data_env_topo_clim$obs@data[, -c(1:5)], data_env_topo_clim$bg@data)
dataset$lf = as.factor(dataset$lf)

```

## modèle
```{r rfmod, fig = TRUE}
library(randomForest)
set.seed(126)
dataset = na.omit(dataset[,-3])
tuneRF(x=dataset[,c(1:(ncol(dataset)-1))],y=as.factor(dataset$response))

rf.ericar<-randomForest(as.factor(response)~.,mtry=4,ntree=1000,data=dataset)


```

```{r rfspat}
rasalti = rast('ras_alti.tif')
library(spatialRF)
dependent.variable.name <- "response"
predictor.variable.names <- colnames(dataset)[-ncol(dataset)]
dataclean = dataset[which(complete.cases(dataset)),]

xy <- data.frame(rbind(
  coordinates(spTransform(data_env_topo_clim$obs , crs(rasalti))),
  coordinates(spTransform(data_env_topo_clim$bg , crs(rasalti)))
   )[which(complete.cases(dataset)),])
colnames(xy) = c("x", "y")
dim(xy)

distance.matrix = dist(xy, diag=T, upper=T)

model.non.spatial <- spatialRF::rf(
  data = dataclean,
  dependent.variable.name = dependent.variable.name,
  predictor.variable.names = predictor.variable.names,
  distance.matrix = as.matrix(dist.mat),
  distance.thresholds = c(5000, 10000),
  xy = xy, 
  seed = 126,
  verbose = TRUE
)

model.spatial = readRDS("model_spatial.rds")

#print_performance(model.spatial)
# 
# spatialRF::rf_evaluate(
#   model.non.spatial,
#   xy = xy,
#   metrics = "auc",
#   verbose = FALSE
# )
```

```{r rfspat performance, fig = TRUE, cache = TRUE, echo=FALSE}
comparison <- spatialRF::rf_compare(
  models = list(
    `Non-spatial` = model.non.spatial,
    `Spatial` = model.spatial
  ),
  xy = xy,
  repetitions = 30,
  training.fraction = 0.8,
  metrics = "r.squared",
  seed = 125
)

```

```{r rfspat importance, fig = TRUE}


p1 <- spatialRF::plot_importance(
  model.non.spatial, 
  verbose = FALSE) + 
  ggplot2::ggtitle("Non-spatial model") 

p2 <- spatialRF::plot_importance(
  model.spatial,
  verbose = FALSE) + 
  ggplot2::ggtitle("Spatial model")

p1 | p2 

```

```{r rfspat response, fig = TRUE}
spatialRF::plot_response_curves(
  model.spatial,
  variables = NULL,
  quantiles = 0.5,
  ncol = 3
)
```


## Predict
```{r predictorT, fig = TRUE}
topo_rast =  rast("_data/predRast_topo.grd")
plot(topo_rast)
```

```{r predictorC, fig = TRUE}
clim_rast = rast("_data/predRast_clim.grd")
plot(clim_rast)
```

```{r predict, fig = TRUE}
rf.predict.ericar= read_stars("rf.predict.ericar.tif")

require(mapview, sf)
mapviewOptions(na.color = "transparent",
               basemaps="OpenStreetMap",
               viewer.suppress=TRUE,
               trim=TRUE)
mapview(rf.predict.ericar)
```